function ItemID(a) { switch (a) {
case "Ab": return "Hiking Boots"; break;
case "Ac": return "Swamp Boots"; break;
case "Ad": return "Mountain Boots"; break;
case "Ae": return "Lava Boots"; break;
case "Af": return "Row Boat"; break;
case "Ag": return "Small Ship"; break;
case "Ah": return "Sail Boat"; break;
case "Aa": return "Travel Boots"; break;
case "Ba": return "Club"; break;
case "Bb": return "Iron Hammer"; break;
case "Bc": return "Fire Axe"; break;
case "Bd": return "Bucket"; break;
case "Be": return "Lantern"; break;
case "Bf": return "Flower"; break;
case "Bg": return "Iron Axe"; break;
case "Bh": return "Axe"; break;
case "Bi": return "Pick Axe"; break;
case "Bj": return "Net"; break;
case "Bk": return "Fishing Pole"; break;
case "Bl": return "Battle Axe"; break;
case "Ca": return "Notes"; break;
case "Cb": return "Flyer"; break;
case "Cc": return "Broken Bronze Sword"; break;
case "Cd": return "Vial"; break;
case "Ce": return "Nite Berry"; break;
case "Cf": return "Skye Nut"; break;
case "Cg": return "Logs"; break;
case "Ch": return "Broken Pick Axe"; break;
case "Ci": return "Dead Player"; break;
case "Cj": return "Broken Axe"; break;
case "Ck": return "Blue Key"; break;
case "Cl": return "Red Key"; break;
case "Cm": return "Wand"; break;
case "Da": return "Silver Key"; break;
case "Db": return "Unknown Potion"; break;
case "Dc": return "Unused Potion"; break;
case "Dd": return "Vial of Water"; break;
case "De": return "Flour"; break;
case "Df": return "Dough"; break;
case "Dg": return "Egg"; break;
case "Dh": return "Tomato"; break;
case "Di": return "Lettuce"; break;
case "Dj": return "Match"; break;
case "Dk": return "Matches"; break;
case "Dl": return "Matches"; break;
case "Dm": return "Wheat"; break;
case "Eb": return "Treasure Chest"; break;
case "Ec": return "Catfish Barrel"; break;
case "Ed": return "Flounder Barrel"; break;
case "Ee": return "Lobster Barrel"; break;
case "Ef": return "Feathers"; break;
case "Eg": return "Arrowheads"; break;
case "Eh": return "Arrows"; break;
case "Ei": return "Bucket of Water"; break;
case "Ej": return "Bucket of Milk"; break;
case "Ea": return "Dragon Egg"; break;
case "Fa": return "Hazmat Suit"; break;
case "Fb": return "Chicken"; break;
case "Fc": return "Swamp Water"; break;
case "Fd": return "Pumpkin"; break;
case "Fe": return "Range Armor"; break;
case "Ff": return "Magic Robes"; break;
case "Fg": return "Monk Robes"; break;
case "Fh": return "Death Robes"; break;
case "Fi": return "Fire Robes"; break;
case "Fj": return "Evil Robes"; break;
case "Ga": return "Raw Salmon"; break;
case "Gc": return "Raw Turkey"; break;
case "Gb": return "Raw Frog Legs"; break;
case "Gd": return "Raw Crab"; break;
case "Ge": return "Raw Carp"; break;
case "Gf": return "Raw Sewer Crawler"; break;
case "Gg": return "Raw Catfish"; break;
case "Gh": return "Raw Flounder"; break;
case "Gi": return "Raw Ham"; break;
case "Gj": return "Raw Lobster"; break;
case "Gk": return "Raw Shark"; break;
case "Gl": return "Raw Lava Crawler"; break;
case "Hd": return "Copper Ore"; break;
case "He": return "Tin Ore"; break;
case "Hf": return "Emerald"; break;
case "Hg": return "Iron Ore"; break;
case "Hh": return "Ruby"; break;
case "Hi": return "Coal"; break;
case "Hj": return "Lodestone"; break;
case "Hk": return "Diamond"; break;
case "Hl": return "Lava Ore"; break;
case "Id": return "Turkey"; break;
case "Ie": return "Pizza"; break;
case "If": return "Bread Dough"; break;
case "Ig": return "Pancake Batter"; break;
case "Ih": return "Cookie Dough"; break;
case "Ja": return "Salmon"; break;
case "Jb": return "Frog Legs"; break;
case "Jc": return "Candy"; break;
case "Jd": return "Crab"; break;
case "Je": return "Carp"; break;
case "Jf": return "Sewer Crawler"; break;
case "Jg": return "Catfish"; break;
case "Jh": return "Flounder"; break;
case "Ji": return "Ham"; break;
case "Jj": return "Lobster"; break;
case "Jk": return "Shark"; break;
case "Jl": return "Lava Crawler"; break;
case "Kd": return "Pizza x4"; break;
case "Ke": return "Cheese"; break;
case "Kf": return "Bread"; break;
case "Kg": return "Pancakes"; break;
case "Kh": return "Cookie"; break;
case "Ki": return "Half a Sandwich"; break;
case "Kj": return "Sandwich"; break;
case "Kk": return "Pizza x1"; break;
case "Kl": return "Pizza x2"; break;
case "Km": return "Pizza x3"; break;
case "La": return "Scrooge Hat"; break;
case "Lb": return "Gold New Year Hat"; break;
case "Lc": return "Sunglasses"; break;
case "Ld": return "Red Bandana"; break;
case "Le": return "Ranger Hat"; break;
case "Lf": return "Crown"; break;
case "Lg": return "Blue Bandana"; break;
case "Lh": return "Christmas Hat"; break;
case "Li": return "Silver New Year Hat"; break;
case "Ma": return "Green Cylon Helm"; break;
case "Mb": return "Yellow Cylon Helm"; break;
case "Mc": return "Bronze Helmet"; break;
case "Md": return "Black Mask"; break;
case "Me": return "Iron Helmet"; break;
case "Mf": return "Clown Wig"; break;
case "Mg": return "Magic Hat"; break;
case "Mh": return "Steel Helmet"; break;
case "Mi": return "Wizard Hat"; break;
case "Mj": return "Lava Helmet"; break;
case "Nb": return "Fire Cape"; break;
case "Nc": return "Leather Armor"; break;
case "Nd": return "Red Armband"; break;
case "Ne": return "Bronze Armor"; break;
case "Nf": return "Quiver"; break;
case "Ng": return "Iron Armor"; break;
case "Nh": return "Magic Cape"; break;
case "Ni": return "Steel Armor"; break;
case "Nj": return "Blue Armband"; break;
case "Nk": return "Lava Armor"; break;
case "Na": return "Hall of Fame Cape"; break;
case "Ob": return "Bronze Shield"; break;
case "Oc": return "Leather Gauntlets"; break;
case "Od": return "Emerald Ring"; break;
case "Oe": return "Iron Shield"; break;
case "Of": return "Steel Shield"; break;
case "Og": return "Ruby Ring"; break;
case "Oh": return "Silver Gauntlets"; break;
case "Oi": return "Lava Shield"; break;
case "Oj": return "Diamond Ring"; break;
case "Oa": return "Gold Gauntlets"; break;
case "Pa": return "Spear"; break;
case "Pb": return "Battle Spear"; break;
case "Pc": return "Fire Spear"; break;
case "Pd": return "Long Bow"; break;
case "Pe": return "Bronze Sword"; break;
case "Pf": return "Emerald Wand"; break;
case "Pg": return "Cross Bow"; break;
case "Ph": return "Iron Sword"; break;
case "Pi": return "Ruby Wand"; break;
case "Pj": return "Steel Sword"; break;
case "Pk": return "Short Bow"; break;
case "Pl": return "Diamond Wand"; break;
case "Pm": return "Lava Sword"; break;
case "Ra": return "Treat Bag"; break;
case "Rb": return "Treat Bag"; break;
case "Rc": return "Death x1"; break;
case "Rd": return "Death x2"; break;
case "Re": return "Death x3"; break;
case "Rf": return "Poisoned Player"; break;
case "Rg": return "Cure Poison x1"; break;
case "Rh": return "Cure Poison x2"; break;
case "Ri": return "Cure Poison x3"; break;
case "Rj": return "Poisoned Arrowhead x1"; break;
case "Rk": return "Poisoned Arrowhead x2"; break;
case "Rl": return "Poisoned Arrowhead x3"; break;
case "Rm": return "Strength x1"; break;
case "Rn": return "Strength x2"; break;
case "Ro": return "Strength x3"; break;
case "Sa": return "Black Hat"; break;
case "Sb": return "Blue Hat"; break;
case "Sc": return "Red Hat"; break;
case "Sd": return "Green Hat"; break;
case "Se": return "Yellow Hat"; break;
case "Sf": return "Purple Hat"; break;
case "Sg": return "Orange Hat"; break;
case "Sh": return "Black Flag"; break;
case "Si": return "Blue Flag"; break;
case "Sj": return "Red Flag"; break;
case "Sk": return "Green Flag"; break;
case "Sl": return "Yellow Flag"; break;
case "Sm": return "Purple Flag"; break;
case "Sn": return "Orange Flag"; break;
case "Ya": return "Badlands"; break;
case "Yb": return "Aggressive"; break;
case "Yc": return "Badlands (Poisoned)"; break;
case "Yd": return "Badlands 00"; break;
case "Ye": return "Switch Off"; break;
case "Yf": return "Switch On"; break;
case "Yg": return "Mountain"; break;
case "Za": return "Nothing"; break;
case "Zb": return "X"; break;
case "Zc": return "Quest Gate"; break;
case "Zd": return "Experience Gate"; break;
case "Ze": return "Teleport"; break;
case "Zf": return "Sign"; break;
case "Zg": return "Pier"; break;
case "Zh": return "City"; break;
case "Zi": return "Fire Pit"; break;
case "Zj": return "Fire"; break;
case "Zk": return "Mysterious Trader"; break;
case "Zl": return "Hidden Mountain Location"; break;
case "Zm": return "Nothing"; break;

case "NPCKing": return "King Que"; break;
case "NPCCeleste": return "Celeste yes"; break;

case "TPORT": return "Teleport"; break;
case "CART": return "Cart"; break;
case "DOOR": return "Door"; break;
case "FOUNTAIN": return "Fountain"; break;
case "FARMHOUSE": return "Farm House"; break;
default: return "ItemID  "+a; break;
}}
